import type { Metadata } from "next";
import "./globals.css";
import { Poppins, Libre_Caslon_Text } from "next/font/google";
import { Layout } from "@/components/layout/layout";

export const metadata: Metadata = {
  title: "À mão",
  description: "Generated by create next app",
};

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400", "500", "700"],
});

const libreCaslonText = Libre_Caslon_Text({
  variable: "--font-libre-caslon-text",
  subsets: ["latin"],
  weight: ["400", "700"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="pt-br"
      className={`${poppins.variable} ${libreCaslonText.variable}`}
    >
      <body>
        <Layout>{children}</Layout>
      </body>
    </html>
  );
}
